[package]
name = "base"
categories = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[features]
default = [
    "sys/default",
    "std",
]
std = [
    "sys/std",
]

[dependencies]
sys = { workspace = true }
